global:
  scrape_interval: 20s
  scrape_timeout: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: node_exporter
    static_configs:
      - targets:
          - node-exporter:9100

  # Spark Streaming Custom Metrics
  - job_name: 'spark-streaming-custom'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Spark Driver UI Metrics
  - job_name: 'spark-driver-ui'
    static_configs:
      - targets: ['host.docker.internal:4040']
    metrics_path: /metrics/prometheus
    scrape_interval: 30s
    scrape_timeout: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: ^metrics_local_\d+_driver_KafkaSourceMetrics_(.+)_(\d+)_consumer_end_offset_Number$
        target_label: topic
        replacement: $1
        action: replace

      - source_labels: [__name__]
        regex: ^metrics_local_\d+_driver_KafkaSourceMetrics_(.+)_(\d+)_consumer_end_offset_Number$
        target_label: partition
        replacement: $2
        action: replace
